name: CI
on:
  workflow_dispatch:

jobs:
  build:
    name: "JUnit 5 Looming (${{ matrix.os }})"
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: oracle-actions/setup-java@v1
        with:
          website: jdk.java.net
          release: loom
      - name: 'Build with Bach'
        run: .bach/bin/bach build
      - name: 'Prepare JUnit Platform Runs'
        run: echo "JUNIT=${JAVA_HOME}/bin/java -Xmx2G --enable-preview --module-path .bach/out/main/classes/java-19-preview:.bach/external-modules --module org.junit.platform.console --details SUMMARY --scan-modules" >> $GITHUB_ENV
      - name: 'Normal Threads running 10.000 tests'
        run: $JUNIT --config virtual=false --config tests=10000
      - name: 'Normal Threads running 100.000 tests'
        run: $JUNIT --config virtual=false --config tests=100000
      - name: 'Virtual Threads running 10.000 tests'
        run: $JUNIT --config virtual=true --config tests=10000
      - name: 'Virtual Threads running 100.000 tests'
        run: $JUNIT --config virtual=true --config tests=100000
      - name: 'Virtual Threads running 1.000.000 tests'
        run: $JUNIT --config virtual=true --config tests=1000000
