name: CI
on:
  workflow_dispatch:

jobs:
  build:
    name: "JUnit 5 Looming (${{ matrix.os }})"
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: oracle
          java-version: 19
      - name: 'Build'
        run: |
          javac --enable-preview --release 19 --module-path lib --module-source-path . --module com.github.sormuras.junit.looming -d classes
          jar --create --file lib/com.github.sormuras.junit.looming.jar -C classes/com.github.sormuras.junit.looming .
      - name: 'Prepare JUnit Platform Runs'
        run: echo "JUNIT=${JAVA_HOME}/bin/java -Xmx2G --enable-preview --module-path lib --module org.junit.platform.console --details SUMMARY --scan-modules" >> $GITHUB_ENV
      - name: 'Normal Threads running 10.000 tests'
        run: $JUNIT --config virtual=false --config tests=10000
      - name: 'Normal Threads running 100.000 tests'
        run: $JUNIT --config virtual=false --config tests=100000
      - name: 'Virtual Threads running 10.000 tests'
        run: $JUNIT --config virtual=true --config tests=10000
      - name: 'Virtual Threads running 100.000 tests'
        run: $JUNIT --config virtual=true --config tests=100000
      - name: 'Virtual Threads running 1.000.000 tests'
        run: $JUNIT --config virtual=true --config tests=1000000
